l_simp_chinese:
 com_topbar_configuration_button_tooltip: "打开顶部栏配置"
 com_topbar_configuration_title: "顶栏配置"
 com_topbar_configuration_current: "当前顶栏"
 com_topbar_configuration_add: "编辑顶栏"
 com_topbar_configuration_always_show: "Always show topbar elements (#r Overlays windows#!)"
 com_topbar_configuration_add_explanation: "使用下面的按钮从顶栏添加或删除顶栏统计。"
 com_topbar_configuration_clear_first_tooltip: "清除顶栏第一行"
 com_topbar_configuration_add_first_tooltip: "将此组件添加到第一行顶栏"
 com_topbar_configuration_remove_first_tooltip: "从第一顶栏行中删除此组件"
 com_topbar_configuration_clear_second_tooltip: "清除顶栏第二行"
 com_topbar_configuration_add_second_tooltip: "将此组件添加到第二行顶栏"
 com_topbar_configuration_remove_second_tooltip: "从第二顶栏行中删除此组件"
 com_topbar_configuration_add_header_source: "组件来源"
 com_topbar_configuration_add_header_element: "顶栏组件"
 com_topbar_configuration_add_header_first: "第一排\n"
 com_topbar_configuration_add_header_second: "第二排\n"